### ISSUE TITLE
Import Chapter Additions :: Update photo and add an example import file

### ISSUE THREAD

**Issue by SteadyCadence** [Cadasta/cadasta-docs#13]
Adding an example file with an updated screenshot will be helpful for those looking to import.

I believe the geometry/coordinates have changed for the imports. I got errors when I used the "SRID" format.  I would need to verify this with the dev team, but I believe that you only have to include the lat lng, like "21.8984 82.90420", for importing points and then add the `geo_type` as `geopoint`.

**Comment by bethschechter** [comment]
@SteadyCadence can I use an example of one of your files that you used to create one of your projects?

**Comment by SteadyCadence** [comment]
@bethschechter Def.  They are in the imports folder in the Demo folder. Ill send it tomorrow.

**Comment by SteadyCadence** [comment]
https://drive.google.com/drive/folders/0Bwu69XKTjUmwWV9tdENwTHd1cTA

**Comment by bethschechter** [comment]
done! though I got a platform error and could not take as many screenshots as I wanted :/
