### ISSUE TITLE
Import Chapter :: Issues users may run into and suggested solutions

### ISSUE THREAD

**Issue by SteadyCadence** [Cadasta/cadasta-docs#14]
The import process can be tricky if there are required fields missing or the values do not match up perfectly.

I suggest we dive into some errors that may occur so that the user is aware of what may happen if the import is not properly formatted/matched up, etc. 

Maybe something like "Common Issue :: Solution" near the bottom of the chapter (it can be an add on or extension). 

Some Common Problems:
1. Too large of an import (imports can only handle so many records at this time)
2. Poorly spelled or not matching field names or values
3. Values that do not map to the choice values listed in the form
4. Mismatched columns (an error in the 2nd step with matching up the column headers to the form names)
5. Improperly formatted geo column
6. Missing required fields (location_type, party_name, tenure_type, party_type, etc)

**Comment by SteadyCadence** [comment]
Select_multiple values must be importing like `"optionA,optionB"`

**Comment by SteadyCadence** [comment]
Upload some good import files.

**Comment by bethschechter** [comment]
Note: if it's in a CSV, then `select_multiple` needs to be a list with quotes around it

**Comment by bethschechter** [comment]
@SteadyCadence I've added this. Closing the issue, but of course reopen or whatever if it needs to be edited when you review.
