### ISSUE TITLE
XLS Forms: Check description of Groups

### ISSUE THREAD

**Issue by bethschechter** [Cadasta/cadasta-docs#25]

**Comment by SteadyCadence** [comment]
I may need some more description on this.  Group on XLS Forms?

**Comment by dpalomino** [comment]
Hi @bethschechter. I think you are referring to the "Group" section in the XLS Form documentation. I've taken a look and I think it's enough, although I'd clearly highlight in the paragraph that these begin_group and end_group clauses should not be edited. And similarly for the repeats section. 

People who is familiar with xlsforms often try to include additional groups or repeats nested within the entities.

**Comment by bethschechter** [comment]
I am talking about these groups in XLSforms

![image](https://cloud.githubusercontent.com/assets/3361475/24417831/c6acb154-139e-11e7-9b60-61f2bc3c0a8e.png)

**Comment by bethschechter** [comment]
Notes: a group is a section / section header. Necessary b/c if there are questions outside of the groups they won't show up in the platform

**Comment by bethschechter** [comment]
added!
