### ISSUE TITLE
GeoODK (GeoTrace Geometry):: Polyline VS Polygon

### ISSUE THREAD

**Issue by SteadyCadence** [Cadasta/cadasta-docs#37]
A number of people seem to be saving polylines instead of polygons.  We should emphasize and clarify the differences 

![polyline-vs-polygon](https://cloud.githubusercontent.com/assets/25337622/24167673/2f963c1a-0e3d-11e7-9ded-80adae507a83.png)

**Comment by bethschechter** [comment]
@SteadyCadence what are the differences you see?

**Comment by SteadyCadence** [comment]
Polygons are connected and have a fill, while polylines show the lines only.
<img width="620" alt="screen shot 2017-03-27 at 10 03 05 pm" src="https://cloud.githubusercontent.com/assets/25337622/24388648/4b67b60c-1339-11e7-95e2-2de7d8f1e2a8.png">

**Comment by bethschechter** [comment]
@SteadyCadence is this also the case in ODK?

**Comment by bethschechter** [comment]
(I am in the air and can't quite seem to get my phone online to check)

**Comment by dpalomino** [comment]
Hi @bethschechter. Yes, it's also happening in ODK (with geotrace option).

**Comment by bethschechter** [comment]
ok, added to both!
