### ISSUE TITLE
GeoODK Setup Chapter :: Emphasize the 's' in https://demo.cadata.org/collect

### ISSUE THREAD

**Issue by SteadyCadence** [Cadasta/cadasta-docs#38]
A number of partners get caught on not including the 's'. 

The error messaging is super unclear and so it would be useful to make sure it emphasized in the docs.

**Comment by wonderchook** [comment]
Might be helpful to explain why the "s" is important in the docs as well. How it helps with the security of their data while be transmitted to Cadasta.

**Comment by bethschechter** [comment]
added to both ODK and GeoODK documentation.
