### ISSUE TITLE
Discussion :: Ambassador Program

### ISSUE THREAD

**Issue by SteadyCadence** [Cadasta/cadasta-docs#40]
I think well-run ambassador programs may be a great way to scale Cadasta.  

We could set up an application process, be selective, have requirements, etc... 
This is a good example:  https://www.specialized.com/us/en/ambassadors/women/application

**Comment by wonderchook** [comment]
@SteadyCadence I agree this idea has potential. I don't think it should be buried in the docs github though. I would suggest writing a short (couple paragraph) draft on what you think this would look like and circulate on slack for feedback.

**Comment by SteadyCadence** [comment]
ok good idea.  Ill close this and write something up end of the week.

**Comment by SteadyCadence** [comment]
Related: https://carto.com/ambassadors/

**Comment by SteadyCadence** [comment]
Moved to https://github.com/Cadasta/cadasta-project-ideas/wiki/Ambassador-Program
