### ISSUE TITLE
Support for Oriya language

### ISSUE THREAD

**Issue by dpalomino** [Cadasta/cadasta-docs#58]
We need to add Oriya language (spoken in Odia, India) to the list of our supported languages here: 
https://github.com/Cadasta/cadasta-platform/blob/fff14c69d400eac82127c17818585ee318392cb4/cadasta/config/settings/languages.py

We are working with a couple of partners in the region potentially using this language. 

ISO-639-1 code is "or".  Reference [here](https://en.wikipedia.org/wiki/Odia_language). ISO-639-2 and ISO-639-3 code is "ori". 

@oliverroick, would it be possible to include this when you have a second, please? Thanks a lot!

**Comment by wonderchook** [comment]
@dpalomino did you mean to put this in the docs repo? Also you could potentially do a pull request yourself through the web interface

**Comment by dpalomino** [comment]
Hi @wonderchook. No, I was meaning just to include the Oriya language in the [languages.py](https://github.com/Cadasta/cadasta-platform/blob/fff14c69d400eac82127c17818585ee318392cb4/cadasta/config/settings/languages.py) file.

I can do the PR by myself if you are comfortable with that (it's just one line change in the code I think).

**Comment by oliverroick** [comment]
Closing this; will be dealt with in https://github.com/Cadasta/cadasta-platform/issues/1826
