### ISSUE TITLE
Link to Questionnaire in Importing Data page doesn't work

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-docs#7]
@nastynoel commented on [Sun Dec 11 2016](https://github.com/Cadasta/cadasta-platform/issues/999)

This link - https://docs.cadasta.org/en/08-upload.html#09-XLSForms.md goes nowhere when I click on it from the Importing Data page

---

@wonderchook commented on [Mon Dec 12 2016](https://github.com/Cadasta/cadasta-platform/issues/999#issuecomment-266495920)

@nastynoel I assume this is documentation?

**Comment by bethschechter** [comment]
fixed!
