### ISSUE TITLE
Incorrect URL - "reach out to us" in user guide

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-docs#8]
@nastynoel commented on [Sun Dec 11 2016](https://github.com/Cadasta/cadasta-platform/issues/998)

On the Importing Data page (https://docs.cadasta.org/en/08-upload.html) of the user guide, the "reach out to us" links all point to this URL.....
 
http//cadasta.org/contact/

**Comment by bethschechter** [comment]
This is fixed!
